version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "app"
  - package-ecosystem: "npm"
    directory: "/webview-ui"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "webview"
